name = "assignment2"
uuid = "7307e571-d49b-4ec4-b85b-4b90db7b936a"
version = "0.1.0"
authors = ["John T. Foster <johntfosterjr@gmail.com>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
